Card15
Radon-Rodion/ITechArt_Lab pull request #10
Opened 2022-01-10 04:26 UTC by Radon-Rodion

2022-01-10 13:11 UTC, stnslvtvrn requested changes

2022-01-10 13:11 UTC, stnslvtvrn commented on src/components/forms/formHeader.tsx
> +export default React.memo(FormHeader);
useless memo

2022-01-10 13:11 UTC, stnslvtvrn commented on src/components/forms/productsFiltration/productsFiltration.tsx
> +export default React.memo(ProductsFiltration, (prevProps, nextProps) => prevProps.filters === nextProps.filters);
useless memo

2022-01-10 13:11 UTC, stnslvtvrn commented on src/elements/formElements/inputText/inputText.tsx
> +export default React.memo(InputText, (prevProps, nextProps) => prevProps.text === nextProps.text);
useless memo

2022-01-10 13:11 UTC, stnslvtvrn commented on src/elements/formElements/inputText/inputTextArea.tsx
> +export default React.memo(InputTextArea, (prevProps, nextProps) => prevProps.text === nextProps.text);
useless

2022-01-10 13:11 UTC, stnslvtvrn commented on src/elements/formElements/pictureChoose/pictureChoose.tsx
> +      // console.log(reader.result);
remove

2022-01-10 13:11 UTC, stnslvtvrn commented on src/elements/formElements/radioButtonGroup/radiobuttonGroup.tsx
> +export default React.memo(RadioButtonGroup);
useless because all ProductsFiltration always rerenders

2022-01-10 13:11 UTC, stnslvtvrn commented on src/elements/formElements/select/select.tsx
> +export default React.memo(Select);
useless

2022-01-12 04:55 UTC, Radon-Rodion commented on src/components/forms/formHeader.tsx
> +export default React.memo(FormHeader);
removed

2022-01-12 04:56 UTC, Radon-Rodion commented on src/components/forms/productsFiltration/productsFiltration.tsx
> +export default React.memo(ProductsFiltration, (prevProps, nextProps) => prevProps.filters === nextProps.filters);
it is prevents rerenders when game cards are created or edited with admin form

2022-01-12 04:57 UTC, Radon-Rodion commented on src/elements/formElements/inputText/inputText.tsx
> +export default React.memo(InputText, (prevProps, nextProps) => prevProps.text === nextProps.text);
removed. Was used on changePassword form, but too rare to keep it

2022-01-12 04:57 UTC, Radon-Rodion commented on src/elements/formElements/inputText/inputTextArea.tsx
> +export default React.memo(InputTextArea, (prevProps, nextProps) => prevProps.text === nextProps.text);
removed

2022-01-12 04:57 UTC, Radon-Rodion commented on src/elements/formElements/pictureChoose/pictureChoose.tsx
> +      // console.log(reader.result);
removed

2022-01-12 04:57 UTC, Radon-Rodion commented on src/elements/formElements/radioButtonGroup/radiobuttonGroup.tsx
> +export default React.memo(RadioButtonGroup);
removed

2022-01-12 04:57 UTC, Radon-Rodion commented on src/elements/formElements/select/select.tsx
> +export default React.memo(Select);
removed

2022-01-12 05:02 UTC, Radon-Rodion commented
Number of products page renders onloaded reduced to 3: on first creating and setting filters, on clearing products list in redux (+localstorage) and on recieving request with adding products to list in redux

2022-01-12 08:30 UTC, stnslvtvrn approved these changes

2022-01-13 06:10 UTC, merged